// import type { Metadata } from "next";
// import "./globals.css";

// import { Manrope } from 'next/font/google';

// const manrope = Manrope({
//   subsets: ['latin'],
//   display: 'swap',
//   weight: ['400', '500', '600', '700']
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" className={manrope.className}>
//       <body>
//         {children}
//       </body>
//     </html>
//   );
// }

import type React from "react"
import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Purpose Lab",
  description: "AI Assistant Interface",
    generator: 'v0.dev'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}



import './globals.css'
